/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include "STD_TYPES.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "NVIC_interface.h"
//#include "main.h"

///* Defines */
#define EXTI0		6
#define EXTI1		7
//
////#define GRP_0		0
////#define SUB_0		0
////#define GRP_1		1
//
//
//int main(void)
//{
//	NVIC_app();
//}
//
//
//
//
//
//void NVIC_app(void)
//{
//	RCC_voidInit();
//	GPIO_voidEnableClock(GPIOA);
//
//	GPIO_voidSetPinDirection(GPIOA, GPIO_u8PIN0, GPIO_PIN_OUTPUT_10MHZ_PUSH_PULL);	// PA0
//	GPIO_voidSetPinDirection(GPIOA, GPIO_u8PIN1, GPIO_PIN_OUTPUT_10MHZ_PUSH_PULL);	// PA1
//
//	NVIC_voidInit();
//
//	NVIC_voidEnableInterrupt(EXTI0);
//	NVIC_voidEnableInterrupt(EXTI1);
//
//	NVIC_voidSetInterruptPriority(EXTI0, 1, 0);	// Set High Priority
//	NVIC_voidSetInterruptPriority(EXTI1, 0, 0);	// Set Low Priority
//
//
//	NVIC_voidSetPendingFlag(EXTI0);	// Enable interrupt 6 by software to call >>> EXTI0_IRQHandler(void);
//
//
//    /* Loop forever */
//	while(1)
//	{
//		asm("NOP");
//	}
//}
//
//
//
//
/////* The best Solution is making Call back function .... with static global pointer */
//void EXTI0_IRQHandler(void)			// Save the format
//{
//	/* Clear Pending Flag */
////	NVIC_voidClearPendingFlag(EXTI0);
//
//	NVIC_voidSetPendingFlag(EXTI1);	// Enable interrupt 7 by software to >>> call EXTI1_IRQHandler(void);
//
//	while(1)
//	{
//		Toggle_Green_Led();
//	}
//}
//
//
//void EXTI1_IRQHandler(void)
//{
//	/* Clear Pending Flag */
////	NVIC_voidClearPendingFlag(EXTI1);
//
//	Toggle_Red_Led();
//}
//
//
//
//
//
//void Delay(u32 Copy_u32T_ms)
//{
//	for(u32 Local_u32Counter = 0; Local_u32Counter < (Copy_u32T_ms * 500); Local_u32Counter++)
//	{
//		asm("NOP");
//	}
//}
//
//
//void Toggle_Green_Led()
//{
//	//GPIO_voidSetPinValue(GPIOA, GPIO_u8PIN0, GPIO_u8PIN_HIGH);
//	GPIO_voidTogglePin(GPIOA, GPIO_u8PIN0);
//	Delay(50);
//	//GPIO_voidSetPinValue(GPIOA, GPIO_u8PIN0, GPIO_u8PIN_LOW);
//	//Delay(100);
//}
//
//
//void Toggle_Red_Led()
//{
//	GPIO_voidTogglePin(GPIOA, GPIO_u8PIN1);
//	Delay(1000);
//	GPIO_voidTogglePin(GPIOA, GPIO_u8PIN1);
//	Delay(1000);
//
////	GPIO_voidSetPinValue(GPIOA, GPIO_u8PIN1, GPIO_u8PIN_HIGH);
////	Delay(100);
////	GPIO_voidSetPinValue(GPIOA, GPIO_u8PIN1, GPIO_u8PIN_LOW);
////	Delay(100);
//}





void Delay (void);
int main(void)
{
	RCC_voidInit();

	GPIO_voidEnableClock(GPIOA);
	GPIO_voidEnableClock(GPIOB);
	GPIO_voidEnableClock(GPIOC);

	GPIO_voidSetPinDirection(GPIOA, GPIO_u8PIN1, GPIO_PIN_OUTPUT_2MHZ_PUSH_PULL);
	GPIO_voidSetPinDirection(GPIOA, GPIO_u8PIN0, GPIO_PIN_OUTPUT_2MHZ_PUSH_PULL);
	GPIO_voidSetPinDirection(GPIOB, GPIO_u8PIN1, GPIO_PIN_OUTPUT_2MHZ_PUSH_PULL);
	NVIC_voidInit();

	NVIC_voidEnableInterrupt(EXTI0);
	NVIC_voidEnableInterrupt(EXTI1);

	NVIC_voidSetInterruptPriority(EXTI0, 1, 0);
	NVIC_voidSetInterruptPriority(EXTI1, 0, 0);

	while(1)
	{
		NVIC_voidSetPendingFlag(EXTI0);
		GPIO_voidTogglePin(GPIOB, GPIO_u8PIN1);
		Delay();
		GPIO_voidTogglePin(GPIOB, GPIO_u8PIN1);
	}
}

void EXTI0_IRQHandler(void) // EXTI0 ==> 6
{
	NVIC_voidSetPendingFlag(EXTI1);
	NVIC_voidClearPendingFlag(EXTI0);
	GPIO_voidSetPinValue(GPIOA, GPIO_u8PIN1, GPIO_u8PIN_HIGH);
	Delay();
	GPIO_voidSetPinValue(GPIOA, GPIO_u8PIN1, GPIO_u8PIN_LOW);
	Delay();
}




void EXTI1_IRQHandler(void)// EXTI1 ==> 7
{
	NVIC_voidClearPendingFlag(EXTI1);
	GPIO_voidSetPinValue(GPIOA, GPIO_u8PIN0, GPIO_u8PIN_HIGH);
	Delay();
	GPIO_voidSetPinValue(GPIOA, GPIO_u8PIN0, GPIO_u8PIN_LOW);
	Delay();


}


void Delay (void)
{
	for(u32 x = 0; x < 200000 ; x++)
	{
		asm("NOP");
	}
}
