/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include "STD_TYPES.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "STK_interface.h"
#include "main.h"


int main(void)
{
	SYSTICK_app();
}





void SYSTICK_app(void)
{
	RCC_voidInit();
	GPIO_voidEnableClock(GPIOA);
	STK_voidInit();

	GPIO_voidSetPinDirection(GPIOA, GPIO_u8PIN0, GPIO_PIN_OUTPUT_10MHZ_PUSH_PULL);	// PA0
	GPIO_voidSetPinDirection(GPIOA, GPIO_u8PIN1, GPIO_PIN_OUTPUT_10MHZ_PUSH_PULL);	// PA1

	//STK_voidSetIntervalSingle(1000000, &Toggle_Green_Led);
	//STK_voidSetIntervalPeriodic(1000000, &Toggle_Green_Led);
	STK_voidSetIntervalPeriodic(1000000, &Task);

    /* Loop forever */
	while(1)
	{
//		Toggle_Green_Led();
//		Toggle_Red_Led();
//		STK_voidDelay_ms(1000);
	}
}




void Task(void)
{
	Toggle_Green_Led();
	Toggle_Red_Led();
}


void Toggle_Green_Led()
{
	GPIO_voidTogglePin(GPIOA, GPIO_u8PIN0);
}


void Toggle_Red_Led()
{
	GPIO_voidTogglePin(GPIOA, GPIO_u8PIN1);
}
