/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../Inc/STD_TYPES.h"
#include "../Inc/BIT_MATH.h"

#include "../Inc/RCC_interface.h"
#include "../Inc/GPIO_interface.h"
#include "../Inc/USART2_interface.h"



#define 	USART2_TX		GPIO_u8PIN2
#define 	USART2_RX		GPIO_u8PIN3


int main(void)
{

	u8 Local_u8RecievedData = 0 ;

	RCC_voidInit();
	RCC_voidEnableClockPeripheral(RCC_BUS_APB2, RCC_APB2_GPIOA);
	RCC_voidEnableClockPeripheral(RCC_BUS_APB1, RCC_APB1_USART2);


	GPIO_voidSetPinDirection(GPIOA, USART2_TX, GPIO_PIN_OUTPUT_2MHZ_AF_PUSH_PULL);	// TX		alternate function
	GPIO_voidSetPinDirection(GPIOA, USART2_RX, GPIO_PIN_INPUT_FLOATING);			// RX

	GPIO_voidSetPinDirection(GPIOA, GPIO_u8PIN0, GPIO_PIN_OUTPUT_2MHZ_PUSH_PULL);	// PA0

	USART2_voidInit();

	while(1)
	{
		Local_u8RecievedData = USART2_u8RecCharSynch();
		if( Local_u8RecievedData == '0')
		{
			GPIO_voidSetPinValue(GPIOA, GPIO_u8PIN0, GPIO_u8PIN_LOW);
		}
		else if(Local_u8RecievedData == '1' )
		{
			GPIO_voidSetPinValue(GPIOA, GPIO_u8PIN0, GPIO_u8PIN_HIGH);
		}
	}

	return 0;
}

