/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "STD_TYPES.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "NVIC_interface.h"
#include "DMA_interface.h"
#include "main.h"

u16 Local_u16Index;


int main(void)
{
	DMA_app();
}




void DMA_app(void)
{
	/* Initialization Part */
	u32 Arr1[1000];
	u32 Arr2[1000] = {0};
	u32 Arr3[1000];
	u32 Arr4[1000] = {0};

	/* Initialize the Array */
	for(u16 i = 0; i < 1000; i++)
	{
		Arr1[i] = i;
		Arr3[i] = i;
	}

	/* System Clock Initialization */
	RCC_voidInit();

	/* Toggle Led C13	GPIOC */
	/* 1- Enable Per Clock "RCC" Port C */
	GPIO_voidEnableClock(GPIOC);

	/* 2- Enable Peripheral clock "RCC" DMA1 */
	DMA_voidEnablelock(DMA1);

	/* Direction for C13 is output Push Pull */
	GPIO_voidSetPinDirection(GPIOC, GPIO_u8PIN13, GPIO_PIN_OUTPUT_2MHZ_PUSH_PULL);

	/* NVIC Initialization */
	NVIC_voidInit();

	/* DMA1 initialization */
	DMA1_voidChannelInit();

	/* DMA1 Channel1 NVIC interrupt Enable */
	NVIC_voidEnableInterrupt(11);


	DMA1_voidChannelStart(Arr1, Arr2, 1000);

	for(Local_u16Index = 0; Local_u16Index < 1000; Local_u16Index++)
	{
		Arr4[Local_u16Index] = Arr3[Local_u16Index];
	}

	while(1)
	{
		/* Toggle led */
		//GPIO_voidTogglePin(GPIOC, GPIO_u8PIN13);
		//STK_voidBusyWait(1000000);
	}
}

void DMA1_Channel1_IRQHandler(void)
{

	/*Clear GIF flag*/
	//DMA1_t->IFCR = 1<<0;		/*Clear Global Interrupt flag of channel1*/
	/*Clear TC flag*/
}
